### ISSUE TITLE
did we update docker when we changed to git-lfs?

### ISSUE THREAD

**Issue by asimonov** [space-ros/simulation#35]
### Version or commit hash

main

### RMW Implementation

CycloneDDS

### Steps to reproduce issue

I have build moveit2>>robots_demo dockers. following instructions here https://github.com/space-ros/docker/tree/main/space_robots

on launching mars rover demo I get this:

```
[ign gazebo-1] [Err] [STLLoader.cc:68] Unable to read STL[/home/spaceros-user/demos_ws/install/simulation/share/simulation/models/curiosity_path/meshes/curiosity_path.stl]
[ign gazebo-1] [Err] [ColladaLoader.cc:401] Unable to load collada file[/home/spaceros-user/demos_ws/install/simulation/share/simulation/models/curiosity_path/meshes/chassis_full_fixed_glitch_v2.dae]
[ign gazebo-1] [Err] [ColladaLoader.cc:405] Missing COLLADA tag
```

turns out:

```
paceros-user@fakie:~/demos_ws$ cat /home/spaceros-user/demos_ws/install/simulation/share/simulation/models/curiosity_path/meshes/chassis_full_fixed_glitch_v2.dae
version https://git-lfs.github.com/spec/v1
oid sha256:5688107dea59af3db76de719aab9029a157b9fda5246e76e0cb7141031a3cbf0
size 2905946
```

so looks like dockers were not updated for git lfs?

### Expected behavior

mars rover demo works

### Actual behavior

mars rover demo fails

**Comment by eholum** [comment]
I believe this should be resolved by https://github.com/space-ros/docker/issues/193, closing for now.
